### ISSUE TITLE
Similarity can exceed 1 if term is missing and parent is present

### ISSUE THREAD

**Issue by michbur** [MEGA-GO/Mega-GO#1]
If a term is missing in the swissprot database but it's parent is present, the best match average can greater than 1. This is caused by the the way the BMA is calculated: the numerator is twice the information content of the lowest common ancestor of the two terms (say 2*0.5), while the denominator is the sum of the information content of the individual terms (0+0.5). In the given example, the resulting BMA would be 2.

Possible solutions:
 - inform the user that the similarity measure cannot be computed;
 - take the closest existing parent (with the lowest/the highest information content).

**Comment by WassimG** [comment]
Solved the issue by replacing the information content with the highest information content of node/term ancestors.
