### ISSUE TITLE
Ideas for heuristics to decrease the number of comparisons.

### ISSUE THREAD

**Issue by rababerladuseladim** [MEGA-GO/Mega-GO#13]
Comparing large sets of GO terms leads to a quadratic explosion required comparisons. This makes analyzing large sets unfeasible, due to enormous run-times. One way to reduce the computational overhead is to try and infer the similarity of two given terms based on heuristics and only calculate the similarity if this fails.

One heuristic is to check the namespace of the terms first and only compare terms if they are from the same namespace.

Any other ideas for sensible heuristics?

**Comment by pverscha** [comment]
I've been working on some optimizations to make our code run faster. The results of these optimizations can be found here: https://docs.google.com/spreadsheets/d/1w-h3woFuB8dNl6yy0zpXZiYp4DMnZtliMO0e4QpWC8E/edit

**Comment by rababerladuseladim** [comment]
Thanks to #24 by pverscha, performance has improved so drastically that we do not need heuristics anymore.
