### ISSUE TITLE
Similarity values of non-comparable GO-term sets

### ISSUE THREAD

**Issue by rababerladuseladim** [MEGA-GO/Mega-GO#9]
The tool reports negative similarity values in some specific cases (cases I could identify are listed below). 

### term vs. term similarity calculation, using Rel_Metric function:
1) GO terms are from different namespaces (*e.g.* molecular function and biological process) -> return -1

### set vs. set similarity calculation, using the best match average (BMA) function: 
2) both sets are empty -> crash (zero division error)
3) one set is empty, the other is not -> return -1
4) all pairwise similarities are -1 -> return -1

The motivation for letting the Rel_Metric function return '-1' instead of None or null was that the max function used in the BMA function will filter these out and does not work for mixed types.

Unfortunately, it leads to some edge cases and I think it will easily introduce bugs if we ever decide to use a different aggregation function than BMA. 

## Proposed solution (suggestions welcome)
Raise an error in the Rel_Metric function and catch it with a try/catch statement in the BMA function. In any newly implemented aggregation function, these error would not be caught and therefore cannot silently pass.

One question remains: What is the similarity of sets that cannot be compared? My gut says to report 0.

**Comment by bmesuere** [comment]
I would only compare stuff from the same namespace and show the end result for the 3 namespaces?

**Comment by rababerladuseladim** [comment]
# term vs. term similarity
Switch from -1 to NaN if two terms are not comparable.

If one of the terms is not found in the GO-DAG at hand, we should also log this. (adresses #12 )

Only compute comparison for terms from the same namespace, yield result per namespace.
